In [2]:
from datasets import load_dataset

dataset = load_dataset("CShorten/ML-ArXiv-Papers")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/986 [00:00<?, ?B/s]

ML-Arxiv-Papers.csv: reconstructing file:   0%|          |  0.00B /  147MB

ML-Arxiv-Papers.csv: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/117592 [00:00<?, ? examples/s]

In [3]:
import pandas as pd
df = dataset["train"].to_pandas()
df.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'title', 'abstract'], dtype='object')

In [4]:
df.sample(10)

,Unnamed: 0.1,Unnamed: 0,title,abstract
59562,59562,59562.0,Meta-Learning Stationary Stochastic Process Pr...,Stationary stochastic processes (SPs) are a ...
61950,61950,61950.0,An Imitation from Observation Approach to Tran...,We examine the problem of transferring a pol...
88539,88539,88539.0,The Contextual Appointment Scheduling Problem,This study is concerned with the determinati...
62315,62315,62315.0,Lie PCA: Density estimation for symmetric mani...,We introduce an extension to local principal...
39955,39955,39955.0,MetalGAN: a Cluster-based Adaptive Training fo...,"In recent years, the majority of works on de..."
43255,43255,43255.0,Enhancing the Privacy of Federated Learning wi...,In response to growing concerns about user p...
90311,90311,90311.0,On the Efficiency of Subclass Knowledge Distil...,This work introduces a novel knowledge disti...
30182,30182,30182.0,Automatic Ontology Learning from Domain-Specif...,Ontology learning is a critical task in indu...
78855,78855,78855.0,Resource-aware Time Series Imaging Classificat...,The number of end devices that use the last ...
112159,112159,112159.0,Time Interval-enhanced Graph Neural Network fo...,Shared-account Cross-domain Sequential Recom...

In [5]:
df = df[['title', 'abstract']]
df=df.head(50000)
df.isnull().sum()

title       0
abstract    0
dtype: int64

In [6]:
df["paper_text"] = df["title"] + " " + df["abstract"]
df

,title,abstract,paper_text
0,Learning from compressed observations,The problem of statistical learning is to co...,Learning from compressed observations The pr...
1,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun...",Sensor Networks with Random Links: Topology De...
2,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...,The on-line shortest path problem under partia...
3,A neural network approach to ordinal regression,Ordinal regression is an important type of l...,A neural network approach to ordinal regressio...
4,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...,Parametric Learning and Monte Carlo Optimizati...
...,...,...,...
49995,"See, Attend and Brake: An Attention-based Sali...",Visual perception is the most critical input...,"See, Attend and Brake: An Attention-based Sali..."
49996,SNIFF: Reverse Engineering of Neural Networks ...,Neural networks have been shown to be vulner...,SNIFF: Reverse Engineering of Neural Networks ...
49997,Beyond Dropout: Feature Map Distortion to Regu...,Deep neural networks often consist of a grea...,Beyond Dropout: Feature Map Distortion to Regu...
49998,A study of resting-state EEG biomarkers for de...,Background: Depression has become a major he...,A study of resting-state EEG biomarkers for de...
49999,Performance Analysis of Combine Harvester usin...,Novel applications of artificial intelligenc...,Performance Analysis of Combine Harvester usin...

In [7]:
df['paper_text'].head()

0    Learning from compressed observations   The pr...
1    Sensor Networks with Random Links: Topology De...
2    The on-line shortest path problem under partia...
3    A neural network approach to ordinal regressio...
4    Parametric Learning and Monte Carlo Optimizati...
Name: paper_text, dtype: object

In [8]:
df[["paper_text"]].head()

                                          paper_text
0  Learning from compressed observations   The pr...
1  Sensor Networks with Random Links: Topology De...
2  The on-line shortest path problem under partia...
3  A neural network approach to ordinal regressio...
4  Parametric Learning and Monte Carlo Optimizati...

In [9]:
print(df['paper_text'].iloc[0])

Learning from compressed observations   The problem of statistical learning is to construct a predictor of a random
variable $Y$ as a function of a related random variable $X$ on the basis of an
i.i.d. training sample from the joint distribution of $(X,Y)$. Allowable
predictors are drawn from some specified class, and the goal is to approach
asymptotically the performance (expected loss) of the best predictor in the
class. We consider the setting in which one has perfect observation of the
$X$-part of the sample, while the $Y$-part has to be communicated at some
finite bit rate. The encoding of the $Y$-values is allowed to depend on the
$X$-values. Under suitable regularity conditions on the admissible predictors,
the underlying family of probability distributions and the loss function, we
give an information-theoretic characterization of achievable predictor
performance in terms of conditional distortion-rate functions. The ideas are
illustrated on the example of nonparametric regression in Gaussian noise.

In [10]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [11]:
print(type(model))

<class 'sentence_transformers.sentence_transformer.model.SentenceTransformer'>

In [12]:
sample_text = df["paper_text"].iloc[0]
sample_text

'Learning from compressed observations   The problem of statistical learning is to construct a predictor of a random\nvariable $Y$ as a function of a related random variable $X$ on the basis of an\ni.i.d. training sample from the joint distribution of $(X,Y)$. Allowable\npredictors are drawn from some specified class, and the goal is to approach\nasymptotically the performance (expected loss) of the best predictor in the\nclass. We consider the setting in which one has perfect observation of the\n$X$-part of the sample, while the $Y$-part has to be communicated at some\nfinite bit rate. The encoding of the $Y$-values is allowed to depend on the\n$X$-values. Under suitable regularity conditions on the admissible predictors,\nthe underlying family of probability distributions and the loss function, we\ngive an information-theoretic characterization of achievable predictor\nperformance in terms of conditional distortion-rate functions. The ideas are\nillustrated on the example of nonparametric regression in Gaussian noise.\n'

In [13]:
df["paper_text"] = df["paper_text"].str.replace("\n", " ", regex=False)
df["paper_text"] = df["paper_text"].str.strip()

In [14]:
sample_text = df["paper_text"].iloc[0]
sample_text

'Learning from compressed observations   The problem of statistical learning is to construct a predictor of a random variable $Y$ as a function of a related random variable $X$ on the basis of an i.i.d. training sample from the joint distribution of $(X,Y)$. Allowable predictors are drawn from some specified class, and the goal is to approach asymptotically the performance (expected loss) of the best predictor in the class. We consider the setting in which one has perfect observation of the $X$-part of the sample, while the $Y$-part has to be communicated at some finite bit rate. The encoding of the $Y$-values is allowed to depend on the $X$-values. Under suitable regularity conditions on the admissible predictors, the underlying family of probability distributions and the loss function, we give an information-theoretic characterization of achievable predictor performance in terms of conditional distortion-rate functions. The ideas are illustrated on the example of nonparametric regression in Gaussian noise.'

In [15]:
embedding = model.encode(sample_text)
print(type(embedding))
print(embedding.shape)

<class 'numpy.ndarray'>
(384,)

In [16]:
embedding[:56]

array([-0.13156408, -0.00678268, -0.00367609,  0.03265162,  0.11219638,
        0.01227266,  0.09816723, -0.09005228,  0.04231165, -0.0197735 ,
       -0.03308417,  0.07452939,  0.10632038, -0.0206043 , -0.02052102,
        0.00169492,  0.07081947,  0.05854449, -0.1123191 ,  0.02082469,
        0.05692545,  0.0201578 ,  0.025831  ,  0.03217029,  0.10513768,
       -0.0967676 ,  0.02700802, -0.0234509 , -0.04549679, -0.01013698,
       -0.01794855, -0.04814427,  0.01077653, -0.03759069,  0.01943478,
        0.0371519 ,  0.02967843,  0.04330944,  0.04373208,  0.03704866,
       -0.00182593,  0.00455186, -0.00799067,  0.03037373, -0.014378  ,
        0.0379515 ,  0.05959161, -0.02583361, -0.0652157 ,  0.05900266,
       -0.02107138,  0.07359428, -0.05720108,  0.0029406 ,  0.00767515,
       -0.03334165], dtype=float32)

In [17]:
sample_embedding = model.encode(
    df["paper_text"].head(5).to_list()
)

print(sample_embedding.shape)

(5, 384)

In [18]:
import sklearn
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity([sample_embedding[0]], [sample_embedding[0]])
print(similarity)

[[1.]]

In [19]:
similarity = cosine_similarity(sample_embedding[0].reshape(1, -1), sample_embedding[1].reshape(1, -1))
print(similarity)

[[0.36625272]]

In [20]:
# 1. Run the import again to fix the NameError
from sklearn.metrics.pairwise import cosine_similarity

# 2. Run your loop
for i in range(1, 5):
    sim = cosine_similarity(sample_embedding[0].reshape(1, -1), sample_embedding[i].reshape(1, -1))
    print(f"Similarity with Paper {i}: {sim[0][0]}")

Similarity with Paper 1: 0.36625272035598755
Similarity with Paper 2: 0.33522841334342957
Similarity with Paper 3: 0.15505117177963257
Similarity with Paper 4: 0.37421536445617676

In [21]:
embedding = model.encode(
    df["paper_text"].to_list(),
    batch_size=32,
    show_progress_bar=True
)

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

In [22]:
import numpy as np
import os
index_path = "arxiv_embeddings.npy"

if os.path.exists(index_path):
    print("Loading saved embeddings")
    embeddings = np.load(index_path)
else:
    print("Generating embeddings")
    embeddings = model.encode(
        df["paper_text"].tolist(),
        batch_size=32,
        show_progress_bar=True
    )
    np.save(index_path, embeddings)
    print("Embeddings saved successfully!")
np.save(index_path, embedding)

print("Embeddings successfully saved to disk!")

Generating embeddings

Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

Embeddings saved successfully!
Embeddings successfully saved to disk!

In [23]:
df.to_csv("cleaned_arxiv_papers.csv", index=False)
print("Cleaned DataFrame saved successfully!")

Cleaned DataFrame saved successfully!